const USER_ONLINE = 'USER_ONLINE'
const RECEIVE_MESSAGE = 'RECEIVE_MESSAGE'
const SEND_MESSAGE = 'SEND_MESSAGE'
const JOIN_CHAT = 'JOIN_CHAT'

module.exports = {
    USER_ONLINE,
    RECEIVE_MESSAGE,
    SEND_MESSAGE,
    JOIN_CHAT
}